### ISSUE TITLE
building it.

### ISSUE THREAD

**Issue by joeblew99** [steveoc64/go-cmms#1]
Could you add something to readme ?

**Comment by joeblew99** [comment]
make is nice make remake ?

**Comment by steveoc64** [comment]
Hiya Joe  :)

Well done on discovering this repo.

There is a fair bit to go in here yet before its generally useable for what you are looking for (that being an example app that uses gopherjs, that does a bit more that a TODO list, or a hello world example).  Getting there.  

In its current state, it is not runnable without the database behind it. I will get in contact with you once I have a sanittzed DB that I can share with you. As you might be able to see, the current setup is heavily customized for one particular customer, and has a fair bit of proprietary whack in it.  Thats cool for now, as there is only this one user of the system, and they are driving the whole thing.  But still, the code should be an interesting read as-is.  There is good work in there that demonstates gobs over RPC to a web browser, and Im pleased to report that that part of the system works really well. Its in a production setting that get hammered daily, and the whole thing holds up well under pressure.

What I ultimately want to do app / repo is generalize it, split it up into a series of blog posts, and run through the concept of how this is supposed to work in a tutorial.  Would love your feedback and input on that.

You will also have to have a look at github.com/steveoc64/formulate   .. which is a super early attempt to write a separate forms library for gopherjs, which aims to manage the horrors of data conversion to-and-from  DOM Elements and Go types. 

Talk soon

**Comment by steveoc64** [comment]
> > make is nice make remake ?

Ah yes - I got sick of porting Grunt to Gulp to whatever is cool next.  Good old Make keeps it simple, and I do like to throw in some audio output in my makefiles so I can "hear" what the build is doing whilst Im looking at something else. Works for me  :)

**Comment by joeblew99** [comment]
Thanks Steve.
Sounds good. If you don't mind I will leave this issue open, to remind you
to get back to me when your ready for some beta tester.

I like the sounds too :)

**Comment by steveoc64** [comment]
@joeblew99 - bump

From commit : 14da82111e7ddc73d394a21241035384b7cf4833
This commit includes a sample database, to get you closer to being able to build and run from this repo.

The data is in the ./database dir from the project root, and it assumes that you have a working PostgreSQL install on your machine.

Still a lot to do before this is close to being an "open source" package, but thankfully you know your way around a computer, so you should be good to go .

Touch base with me when you hit the next snag, cheers.

**Comment by joeblew99** [comment]
Ok cheers. Have travel for next week and will try it out and get back to
you.

**Comment by joeblew99** [comment]
Will do thanks
